### PR TITLE
check for external ID or throw error

### LINKED ISSUE #14: Event delivery to Segment fails if ticket requester has no external_id
to: @wcpines 

The error thrown when the ticket `requester` has no external ID (i.e., in our case, Aptible user ID)

```
2015-08-03 23:02:49 - ArgumentError - Must supply either user_id or anonymous_id:
	/usr/lib/ruby/gems/2.1.0/gems/analytics-ruby-2.0.12/lib/segment/analytics/client.rb:343:in `check_user_id!'
```

So I think we should:

* [x] Programmatically backload all existing external IDs in Zendesk (I can help with this)
* [x] Enable Segment-to-Zendesk integration going forward, to automatically populate future external IDs
* [x] To help in debugging, fail with an exception that includes the ticket ID when `external_id` is absent. For example: 

    ```ruby
    fail "Failed to process ticket #{ticket.id}: no external ID" unless requester.external_id
    ```

### PR DESCRIPTION
**Pull request by wcpines**
Fixes #14

### CODE REVIEW

File: backload.rb [hunk 1]
```diff
@@ -11,7 +11,9 @@ def load!
     next unless status == 'Closed' && group == 'Support'
     ticket_metrics = ticket.metrics
     requester = ticket.requester
-    next unless requester.external_id
```
Comment (fancyremarker) [inline backload.rb]: Let's be less aggressive in the `backload` function, since some users will not have external IDs for a variety of reasons, and we won't want to fail the entire script if a single user doesn't have an external ID. Something like the following would work:

```
unless requester.external_id
  puts "Failed to process ticket #{ticket.id}: no external ID"
  next
end
```

**Comment by fancyremarker** [comment]
Great, merging. We will need to re-run this now.
